/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module rom1_12 (
    input [4:0] selector,
    output reg [37:0] out
  );
  
  
  
  localparam INPUTS = 1102'h2000000209fffe000220015c00088001c000b8a0010002a30f04000884003c0012033c4003b69c91a1e0594e8b64a95c280024011518449b858521000e5e0406043b600090006f700000000dc00000007700010000d400000007540158000cc00ec00ef300010001060001fffc17fffffff0400ec00901000000000211271c0c0600127cb00005407ec0;
  
  always @* begin
    out = INPUTS[(selector)*38+37-:38];
  end
endmodule
