/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare_16_11 (
    input z,
    input v,
    input n,
    input [0:0] sim_error,
    input [5:0] alufn,
    output reg [15:0] out
  );
  
  
  
  always @* begin
    out = 16'h0000;
    
    case (alufn[0+3-:4])
      default: begin
        out[0+0-:1] = 1'h0;
      end
      4'h3: begin
        if (sim_error == 1'h0) begin
          out[0+0-:1] = z;
        end else begin
          out[0+0-:1] = ~z;
        end
      end
      4'h5: begin
        if (sim_error == 1'h0) begin
          out[0+0-:1] = n ^ v;
        end else begin
          out[0+0-:1] = ~(n ^ v);
        end
      end
      4'h7: begin
        if (sim_error == 1'h0) begin
          out[0+0-:1] = z | (n ^ v);
        end else begin
          out[0+0-:1] = ~(z | (n ^ v));
        end
      end
    endcase
  end
endmodule
