/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module rom2_13 (
    input [4:0] selector,
    output reg [18:0] out
  );
  
  
  
  localparam INPUTS = 551'h08002fffc2015c380007ff00000f001e00cf1043c08bb761e9fe060f00a5e80402000000000600009000000002400018000c000080002a0001800b8000089698a1f3181080;
  
  always @* begin
    out = INPUTS[(selector)*19+18-:19];
  end
endmodule
